### ISSUE TITLE
deprecated function

### ISSUE THREAD

**Issue by sioodmy** [articblush/articblush.nvim#3]
newest neovim returns this error 
```
vim.highlight.create is deprecated, use vim.api.nvim_set_hl instead. See :h deprecated
This function will be removed in Nvim version 0.9
stack traceback:
        ...nwrapped-master/share/nvim/runtime/lua/vim/highlight.lua:14: in function 'hi'
        .../vimplugin-articblush-nvim/lua/articblush/highlights.lua:8: in function 'highlight_all'
        .../start/vimplugin-articblush-nvim/lua/articblush/init.lua:20: in function 'setup'
        /home/sioodmy/.config/nvim/lua/core/options.lua:58: in main chunk
        [C]: in function 'require'
        /home/sioodmy/.config/nvim/config.lua:3: in main chunk
```

**Comment by AlphaTechnolog** [comment]
> newest neovim returns this error
> 
> ```
> vim.highlight.create is deprecated, use vim.api.nvim_set_hl instead. See :h deprecated
> This function will be removed in Nvim version 0.9
> stack traceback:
>         ...nwrapped-master/share/nvim/runtime/lua/vim/highlight.lua:14: in function 'hi'
>         .../vimplugin-articblush-nvim/lua/articblush/highlights.lua:8: in function 'highlight_all'
>         .../start/vimplugin-articblush-nvim/lua/articblush/init.lua:20: in function 'setup'
>         /home/sioodmy/.config/nvim/lua/core/options.lua:58: in main chunk
>         [C]: in function 'require'
>         /home/sioodmy/.config/nvim/config.lua:3: in main chunk
> ```
oh, lmao.
well i'll update this ASAP, thanks you for reporting!!
