### ISSUE TITLE
Broken cursor line with indentline plugin

### ISSUE THREAD

**Issue by sioodmy** [articblush/articblush.nvim#4]
![image](https://user-images.githubusercontent.com/81568712/183361843-36d09ff3-c247-4906-befe-f8b5f78dc56c.png)

**Comment by AlphaTechnolog** [comment]
that just happens with articblush.nvim? did you tried with another colorscheme to check if it's an articblush.nvim issue? or just a issue with the plugin? also what plugin is that?

**Comment by sioodmy** [comment]
>that just happens with articblush.nvim? 

yes 

>also what plugin is that?

[indentLine](https://github.com/Yggdroot/indentLine/)

**Comment by AlphaTechnolog** [comment]
Oh, F, can u gimme the link for another colorscheme that don't have this problem?

**Comment by sioodmy** [comment]
https://github.com/catppuccin/nvim/

actually i sent wrong link to the plugin https://github.com/lukas-reineke/indent-blankline.nvim/
sorry

**Comment by AlphaTechnolog** [comment]
Ah ok, I'll check it later xd

**Comment by tamton-aquib** [comment]
Heyyo this can probably be solved by setting the `bg` of `IndentBlanklineChar` to none.

**Comment by AlphaTechnolog** [comment]
> Heyyo this can probably be solved by setting the `bg` of `IndentBlanklineChar` to none.

Thank you, that solved the issue! :>
